import math

print(">>====================================<<")
print("||                                    ||")
print("||  Welcome to Dek Depe's Calculator  ||")
print("||                                    ||")
print(">>====================================<<")
print("\n")
nama = input("Nama : ")
tanggal_lahir = input("Tanggal Lahir : ")
jurusan = input("Jurusan : ")
kelompok_mentoring = int(input("Kelompok Mentoring : "))
motto = input("Motto : ")
alas = int(input("Masukkan alas (cm) : "))
tinggi = int(input("Masukkan tinggi (cm) : "))
miring = math.sqrt(math.pow(alas,2) + math.pow(tinggi,2))
luas = alas * tinggi / 2
keliling = math.ceil(alas + tinggi + miring)
print("\n")
print("Halo " + nama + " dari jurusan " + jurusan + ".")
print(nama + " berasal dari kelompok mentoring " + str(kelompok_mentoring) + ".")
print(nama + " lahir pada " + tanggal_lahir + " dengan moto " + motto + ".")
print("Luas dari segitiga yang dimiliki " + nama + " adalah " + str(luas) + " cm^2.")
print("Keliling dari segitiga yang dimiliki " + nama + " adalah " + str(keliling) + " cm dengan sisi miring sepanjang " + str(miring) + ".")
print("\n")
print(">>==========================================<<")
print("||                                          ||")
print("||  Thanks for using Dek Depe's Calculator  ||")
print("||                                          ||")
print(">>==========================================<<")